
// QuillSimpleToolbar(
//   controller: _controller,
//   configurations: const QuillSimpleToolbarConfigurations(
//     showFontFamily: false,
//     showFontSize: false,
//     showInlineCode: false,
//     showLink: false,
//     showListCheck: false,
//     showListBullets: false,
//     showListNumbers: false,
//     showColorButton: false,
//     showBackgroundColorButton: false,
//     showSearchButton: false,
//     showIndent: false,
//     showDirection: false,
//     showAlignmentButtons: false,
//     showSmallButton: false,
//     showLineHeightButton: false,
//     showHeaderStyle: false,
//     showClipboardCut: false,
//     showClipboardCopy: false,
//     showClipboardPaste: false,
//     showClearFormat: false,
//     showQuote: false,
//   ),
// ),
